name: main-worklfow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    setps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"
      - name: Print Go version
        run: go versionn
      - name: Run unit tests
        run: go test -v ./...
